### ISSUE TITLE
Consider marking this output value as sensitive

### ISSUE THREAD

**Issue by michaelnoonan** [andrewsav-bt/vault-octopus#1]
Regarding https://github.com/andrewsav-datacom/vault-octopus/blob/e67d45bd42370c41a01b9fc1876a459b60215ada/vault-get-secret.ScriptBody.ps1#L91 - consider marking this as a sensitive output variable. The effect of this is that the variable will be masked in any logs, and propagated through the Octopus deployment pipeline as a sensitive value. This lessens the risk of sensitive values being exposed.

https://octopus.com/docs/deployment-process/variables/output-variables#sensitive-output-variables

We shipped this in https://github.com/OctopusDeploy/Issues/milestone/370 as part of https://github.com/OctopusDeploy/Issues/issues/4541

**Comment by AlexAkulov** [comment]
Any progress?
